### ISSUE TITLE
Decoding authenticode pkcs#7 signedData blob

### ISSUE THREAD

**Issue by requaos** [mozilla-services/pkcs7#15]
There is an explicit expectation for the final `PKCS7.Content` to be an Octet String (tag: 4), where in the authenticode signature block found at the tail of signed binaries on the windows platform, is a Sequence (tag: 16). 
In the case of a Sequence, the `PKCS7.Content` should be set to the `content.FullBytes` value.

**Comment by g-k** [comment]
Fixed in https://github.com/mozilla-services/pkcs7/pull/16

Thanks!
