### ISSUE TITLE
asn.1: EncryptedContent should not be marked explicit

### ISSUE THREAD

**Issue by davidzech** [mozilla-services/pkcs7#37]
```
	EncryptedContent           asn1.RawValue `asn1:"tag:0,optional,explicit"
```
Is incorrect

**Comment by roosr** [comment]
I also ran into this bug which is causing me some issues for an application I am working on. There is also a BER vs DER issue when creating an EnvelopedData type. Would anyone mind if I push up PR to fix both issues?

**Comment by antoinedeschenes** [comment]
Confirmed having trouble with envelopedData. In the original repository this is forked from, this work properly:
```
	EncryptedContent           asn1.RawValue `asn1:"tag:0,optional"`
```

**Comment by antoinedeschenes** [comment]
#40 seems to fix this
