### ISSUE TITLE
catch up to fullsailor upstream

### ISSUE THREAD

**Issue by g-k** [mozilla-services/pkcs7#60]
Review and land any patches we might be missing from fullsailor/pkcs7 upstream.

**Comment by andlabs** [comment]
Hi. We have internally found that the writes to the unused debugging variable `encodeIndent` in `ber.go` are raising thread sanitizer alarms when run in a parallel test suite. This has already been fixed upstream: https://github.com/fullsailor/pkcs7/commit/d7302db945fa6ea264fb79d8e13e931ea514a602. Could this commit be cherrypicked at the least? It'll be faster than sending another patch that does the same thing. Thanks!
