### ISSUE TITLE
encryptedContent data in EncryptedContentInfo should be encoded as "implicit" not "explicit"

### ISSUE THREAD

**Issue by grk-it** [mozilla-services/pkcs7#84]
The encryptedContent field in EncryptedContentInfo is "implicit" according to the rfc (https://www.rfc-editor.org/rfc/rfc5652).

EncryptedContentInfo ::= SEQUENCE {
        contentType ContentType,
        contentEncryptionAlgorithm ContentEncryptionAlgorithmIdentifier,
        encryptedContent [0] IMPLICIT EncryptedContent OPTIONAL }

However, marshalEncryptedContent() is emitting encryptedContent as EXPLICIT and it can't be parsed by strict parsers.

**Comment by jessepeterson** [comment]
I recall this issue from forever ago: https://github.com/fullsailor/pkcs7/issues/31

But I'd also check out #73 for a better maintained fork of this project.
